# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='playlist_app.Playlist'),
        ),
        migrations.AlterField(
            model_name='listener',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_playlists', to='user_app.User'),
        ),
    ]
